# Generated by Django 3.1.3 on 2020-11-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hot_res_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
