# Generated by Django 3.1.3 on 2020-11-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_res_app', '0002_auto_20201108_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='hot_res_djng/hot_res_app/static/hot_res_app/images/categories'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='hot_res_djng/hot_res_app/static/hot_res_app/images/menu_items'),
        ),
    ]
