# Generated by Django 3.1.3 on 2020-12-14 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hot_res_app', '0003_auto_20201119_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField()),
                ('date_time_started', models.DateTimeField()),
                ('date_time_completed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='is_awailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='hot_res_app/static/hot_res_app/images/categories'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='hot_res_app/static/hot_res_app/images/menu_items'),
        ),
    ]
