# Generated by Django 3.1.3 on 2021-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_res_app', '0005_auto_20201214_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='hot_res_app/static/hot_res_app/images/qr_codes'),
        ),
    ]
