# Generated by Django 3.1.3 on 2021-02-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_res_app', '0007_auto_20210208_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.URLField(default='192.168.0.110:8000/<bound method Field.value_from_object of <django.db.models.fields.CharField>>'),
        ),
    ]
