# Generated by Django 3.1.3 on 2021-02-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_res_app', '0008_auto_20210208_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.URLField(default='http://192.168.0.110:8000/'),
        ),
    ]
