# Generated by Django 3.1.3 on 2021-02-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_res_app', '0010_auto_20210215_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_order',
            name='place',
            field=models.CharField(default='', max_length=31),
        ),
    ]
